# -*- coding: utf-8 -*-
"""IASP_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7tXXhY4q2Y2gQRex06GU7saGXFMZ_z8
"""

import numpy as np
import cv2
from skimage.util import view_as_windows
from skimage.metrics import structural_similarity as ssim
from sklearn.linear_model import OrthogonalMatchingPursuit
import os

# =========================
# 1. Utility
# =========================

def normalize_columns(A):
    return A / (np.linalg.norm(A, axis=0, keepdims=True) + 1e-8)

def add_noise(img, sigma):
    noise = np.random.randn(*img.shape) * sigma
    return np.clip(img + noise, 0, 255)

# =========================
# 2. Patch Handling
# =========================

def extract_patches(img, patch_size=8):
    patches = view_as_windows(img, (patch_size, patch_size))
    patches = patches.reshape(-1, patch_size * patch_size)
    return patches.T

def reconstruct_image(patches, image_shape, patch_size=8):
    h, w = image_shape
    reconstructed = np.zeros((h, w))
    weight = np.zeros((h, w))

    idx = 0
    for i in range(h - patch_size + 1):
        for j in range(w - patch_size + 1):
            patch = patches[:, idx].reshape(patch_size, patch_size)
            reconstructed[i:i+patch_size, j:j+patch_size] += patch
            weight[i:i+patch_size, j:j+patch_size] += 1
            idx += 1

    return reconstructed / (weight + 1e-8)

# =========================
# 3. DL-SBL Algorithm
# =========================

def initialize_dictionary(m, N):
    A = np.random.randn(m, N)
    return normalize_columns(A)

def dl_sbl(Y, N=128, sigma2=400, max_iter=20):
    m, K = Y.shape
    A = initialize_dictionary(m, N)
    gamma = [np.ones(N) for _ in range(K)]

    for _ in range(max_iter):
        mu_list = []
        Sigma_list = []

        # E-step
        for k in range(K):
            Gamma = np.diag(gamma[k])
            Phi = np.linalg.inv(sigma2*np.eye(m) + A @ Gamma @ A.T)

            Sigma_k = Gamma - Gamma @ A.T @ Phi @ A @ Gamma
            mu_k = (1/sigma2) * Sigma_k @ A.T @ Y[:, k]

            mu_list.append(mu_k)
            Sigma_list.append(Sigma_k)

        # M-step
        for k in range(K):
            gamma[k] = np.diag(
                np.outer(mu_list[k], mu_list[k]) + Sigma_list[k]
            )

        # Dictionary update
        Sigma = sum(
            Sigma_list[k] + np.outer(mu_list[k], mu_list[k])
            for k in range(K)
        )
        M = np.column_stack(mu_list)

        for i in range(N):
            v = Y @ M.T[:, i]
            for j in range(N):
                if j != i:
                    v -= Sigma[i, j] * A[:, j]

            if np.linalg.norm(v) > 1e-8:
                A[:, i] = v / np.linalg.norm(v)

    return A

# =========================
# 4. OMP (Correct Reconstruction)
# =========================

def omp_sparse_coding(A, Y, sparsity=5):
    K = Y.shape[1]
    N = A.shape[1]
    X = np.zeros((N, K))

    omp = OrthogonalMatchingPursuit(n_nonzero_coefs=sparsity)

    for k in range(K):
        omp.fit(A, Y[:, k])
        X[:, k] = omp.coef_

    return X

# =========================
# 5. Metrics
# =========================

def psnr(original, reconstructed):
    mse = np.mean((original - reconstructed) ** 2)
    return 10 * np.log10(255**2 / (mse + 1e-8))

def compute_ssim(img1, img2):
    return ssim(img1, img2, data_range=img2.max() - img2.min())

# =========================
# 6. Process Image
# =========================

def process_image(path, output_folder):
    print(f"\nProcessing: {path}")

    img = cv2.imread(path, 0).astype(np.float32)

    # Resize for stability
    img = cv2.resize(img, (128, 128))

    sigma = 20
    noisy = add_noise(img, sigma)

    # ===== TRAINING (subset for speed) =====
    Y_train = extract_patches(noisy, 8)
    Y_train = Y_train[:, :5000]

    # Learn dictionary
    A = dl_sbl(Y_train, N=128, sigma2=sigma**2)

    # ===== RECONSTRUCTION (FULL PATCHES) =====
    Y_full = extract_patches(noisy, 8)

    # OMP sparse coding
    X_full = omp_sparse_coding(A, Y_full, sparsity=5)

    # Reconstruct patches
    recon_patches = A @ X_full

    # Rebuild image
    reconstructed = reconstruct_image(recon_patches, (128,128), 8)

    # Metrics
    psnr_val = psnr(img, reconstructed)
    ssim_val = compute_ssim(img, reconstructed)

    print("PSNR:", psnr_val)
    print("SSIM:", ssim_val)

    # Save outputs
    base = os.path.basename(path).split('.')[0]

    cv2.imwrite(f"{output_folder}/{base}_original.png", img)
    cv2.imwrite(f"{output_folder}/{base}_noisy.png", noisy)
    cv2.imwrite(f"{output_folder}/{base}_reconstructed.png", reconstructed)

# =========================
# 7. MAIN
# =========================

if __name__ == "__main__":

    image_paths = [
        "shoe.png",
        "hat.png",
        "cube.png",
        "cone.png"
    ]

    output_folder = "results"
    os.makedirs(output_folder, exist_ok=True)

    for path in image_paths:
        process_image(path, output_folder)

    print("\nDone. Check 'results' folder.")

import shutil
from google.colab import files

# Create a zip of the folder
shutil.make_archive('results', 'zip', '/content/results')

# Download the zip
files.download('results.zip')